# --- build stage ---
FROM node:22-alpine AS build
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm ci

COPY . .

ARG VITE_FIREBASE_API_KEY=demo-key
ARG VITE_FIREBASE_AUTH_DOMAIN=demo.firebaseapp.com
ARG VITE_FIREBASE_PROJECT_ID=demo-datasetdeal
ARG VITE_FIREBASE_STORAGE_BUCKET=demo-datasetdeal.appspot.com
ARG VITE_FIREBASE_MESSAGING_SENDER_ID=000000000000
ARG VITE_FIREBASE_APP_ID=1:000000000000:web:000000000000
ARG VITE_USE_FIREBASE=false
ARG VITE_USE_EMULATORS=false
ARG VITE_FIREBASE_EMULATOR_HOST=127.0.0.1

ENV VITE_USE_FIREBASE=$VITE_USE_FIREBASE
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_USE_EMULATORS=$VITE_USE_EMULATORS
ENV VITE_FIREBASE_EMULATOR_HOST=$VITE_FIREBASE_EMULATOR_HOST

RUN npm run build

# --- run stage ---
FROM nginx:1.27-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 8080
